name: Run Ansible Playbook
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible-playbook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Ansible
      run: sudo apt-get install -y ansible

    - name: Create vault password file
      run: echo "${{ secrets.VAULT_PASSWORD }}" > vault_pass.txt

    - name: Run Ansible Playbook
      run: ansible-playbook your-playbook.yml --vault-password-file vault_pass.txt
